DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS post;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE post (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  author_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  title TEXT NOT NULL,
  body TEXT NOT NULL,
  FOREIGN KEY (author_id) REFERENCES user (id)
);

CREATE TABLE expense {
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  category VARCHAR NOT NULL,
  expense FLOAT(2) NOT NULL,
  date  DATE() NOT NULL,
  comment TEXT NOT NULL
}

CREATE TABLE income {
   id INTEGER PRIMARY KEY AUTOINCREMENT,
   category VARCHAR NOT NULL,
   income FLOAT(2) NOT NULL,
   date  DATE() NOT NULL,
   comment TEXT NOT NULL
}
